version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Skipping tests for now due to Node.js compatibility...
      # - npm run test -- --run
      - echo Running linter...
      - npm run lint
  build:
    commands:
      - echo Building application...
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully!
      # CloudFront invalidation temporarily disabled due to permissions
      # - aws cloudfront create-invalidation --distribution-id ECRP51AK9PYZS --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: dist
cache:
  paths:
    - 'node_modules/**/*'
